# Generated by Django 3.2.9 on 2021-11-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pratico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
