# Generated by Django 3.2.9 on 2021-11-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pratico', '0002_album_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('director', models.CharField(max_length=256)),
                ('art', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='album',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
